version: "3.0"
services:
  security:
    build: .
    image: rf
    container_name: rf
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - "usr/src/app/node_modules"
    ports:
      - 4000:4000
    environment:
      - DB_NAME=rf
      - DB_USER=ye
      - DB_PASS=yourcarcrashedl0l
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network
  db:
    build: ./docker/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:8080
    depends_on:
      - app
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge
